# GENERAL -----------------------------------
domain: "gardencruz.com"
logs_error: "App/Logs/logs_error.txt"

# URL ---------------------------------------
url:
  max_length: 256
  max_levels: 5
  min_level_length: 1
  max_level_length: 32
  max_get_params: 8
  max_get_param_name: 32
  max_get_size: 256
  max_post_params: 64
  max_post_size: 2048
  max_post_array_size: 10
  max_post_param_name: 32

email:
  imap:
    server: pop.1and1.com
    port: 995
    protocol: POP3
    flag: 'ssl'
    user: services@gardencruz.com
    pass: Susel2022*
    set_protocol: true
    set_flag: true
  smtp:
    server: smtp.1and1.com
    port: 465

cache:
  class: FileCache
  master_key: master_global
  expire_time: 86400
  prefix: _cache

validation:
  default_language: 'en'

date:
  default_date_format: 'Y-m-d'
  default_datetime_format: 'Y-m-d H:i:s'

security:
  csrf_expire: 7200

# ROUTING ------------------------------------
routing:
  cmd.gardencruzcompany.com: 'cmd/_config/router.yaml'

  gardencruz.com: 'GardenCruz/_config/router.yaml'
  gardencruzcompany.com: 'GardenCruz/_config/router.yaml'

  admin.gardencruz.com: 'Admin/_config/router.yaml'
  admin.gardencruzcompany.com: 'Admin/_config/router.yaml'

  workers.gardencruz.com: 'Worker/_config/router.yaml'
  workers.gardencruzcompany.com: 'Worker/_config/router.yaml'

  clients.gardencruz.com: 'Client/_config/router.yaml'
  clients.gardencruzcompany.com: 'Client/_config/router.yaml'

# LANGUAGES -----------------------------------
languages:
  list: [en, es]
  en:
    name: "English"
  es:
    name: "Español"

default_language: en
