# GENERAL -----------------------------------
domain: "arkit.com"
logs_error: "App/Logs/logs_error.txt"

# URL ---------------------------------------
url:
  # Maximum number of characters of the url
  max_length: 256
  # Maximum numbers of get parameters
  max_get_params: 8
  # Maximum get parameter name size
  max_get_name_size: 16
  # Maximum get parameter value size
  max_get_value_size: 64
  # Maximum number of parameters sent by post
  max_post_params: 64
  # Maximum size for a post parameter
  max_post_value_size: 2048
  # Maximum number of characters for post parameter name
  max_post_name_size: 32
  # Regular expression for post parameters name
  post_param_name_format: [a-zA-Z0-9_.-]
  # Maximum elements count for array sent by post
  max_post_array_size: 10

# LOGS ---------------------------------------
logs:
  # Logs handler
  # Enabled classes: File
  handler: File
  # Destination for logs, according the handler
  logs_destination: App/logs/
  # Destination for logs, according the handler
  errors_destination: App/logs/errors.log
  # Responsible to send the email
  responsible_email: ymlee0919@gmail.com;flpmireles@gmail.com

# CACHE ---------------------------------------
cache:
  # Cache file class
  # Enabled classes: Apc, File, Memcache, Memcached
  handler: File
  # Key for cache
  master_key: master_global
  # Expire time for cache in seconds (default 86400 = 24H)
  expire_time: 86400
  # Prefix
  prefix: _cache

# VALIDATION ----------------------------------
validation:
  # Default language for error messages
  default_language: 'en'
  # Default date format
  default_date_format: 'd-m-Y'
  # Default date time format
  default_datetime_format: 'd-m-Y H:i:s'

# ENVIRONMENT ---------------------------------
env:
  time_zone: America/Havana

email:
  imap:
    server: pop.1and1.com
    port: 995
    protocol: POP3
    flag: 'ssl'
    user: services@gardencruz.com
    pass: Susel2022*
    set_protocol: true
    set_flag: true
  smtp:
    server: smtp.1and1.com
    port: 465

security:
  csrf_expire: 7200
