# GENERAL -----------------------------------
# Important to update it with the current domain.
domain: "landscaping.com"

# URL ---------------------------------------
request:
  # Maximum number of characters of the url
  max_length: 256
  # Maximum numbers of get parameters
  max_get_params: 8
  # Maximum get parameter name size
  max_get_name_size: 16
  # Maximum get parameter value size
  max_get_value_size: 64
  # Maximum number of parameters sent by post
  max_post_params: 64
  # Maximum size for a post parameter
  max_post_value_size: 2048
  # Maximum number of characters for post parameter name
  max_post_name_size: 32
  # Regular expression for post parameters name
  post_param_name_format: '[a-zA-Z0-9_.\-]+'
  # Maximum elements count for array sent by post
  max_post_array_size: 10

# LOGS ---------------------------------------
# Define handlers for internal system logs, each one need:
# - the handler name (available File, Email)
# - configuration (according the handler)
# - array of levels that manage (Request, Info, Notice, Warning, Alert, Debug, Error)
logs:
  handlers:
    1:
      name: File
      config:
        output_directory: resources/logs/
      levels: [Request, Info, Notice, Warning, Alert, Debug, Error]
    2:
      name: Email
      config:
        destination_email: ymlee0919@gmail.com;flpmireles@gmail.com
        sender_account: no-reply@gardencruz.com
      levels: [Error]

# CACHE ---------------------------------------
cache:
  # Cache file class
  # Enabled classes: Apc, File, Memcache, Memcached
  handler: Apc
  # Key for cache
  master_key: ArkitCache
  # Expire time for cache in seconds (default 86400 = 24H)
  expire_time: 86400
  # Prefix
  prefix: TheCache.

# SESSION ----------------------------------
session:
  # The session cookie name, must contain only [0-9a-z_-] characters
  name: account
  # The number of SECONDS you want the session to last.
  # Setting it to 0 (zero) means expire when the browser is closed.
  life_time: 0
  # Seconds between to regenerating the session ID
  time_to_update: 300


# FORM VALIDATION ------------------------------
validation:
  # Default language for error messages
  default_language: 'en'
  # Default date format
  default_date_format: 'd-m-Y'
  # Default date time format
  default_datetime_format: 'd-m-Y H:i:s'
  ## Values for Cross Site Request Forgery
  CSRF:
    # Time to expire CSRF code (seconds)
    expire: 7200
    # Length for private csrf code
    private_key_length: 32
    # Default hidden field name for the token
    field_name: _token_
    # Prefix for cookie implementing the CSRF
    cookie_prefix: field_

# CRYPT ---------------------------------------
crypt:
  hash_algo: gost-crypto

# ENVIRONMENT ---------------------------------
env:
  time_zone: America/Havana

email:
  imap:
    server: pop.1and1.com
    port: 995
    protocol: POP3
    flag: 'ssl'
    user: services@gardencruz.com
    pass: Susel2022*
    set_protocol: true
    set_flag: true
  smtp:
    server: smtp.1and1.com
    port: 465
