# ROUTING ------------------------------------
cmd.landscaping.com: 'CMD/_config/router.yaml'

admin.landscaping.com: 'Admin/_config/router.yaml'
dashboard.landscaping.com: 'Management/_config/router.yaml'