# URL ---------------------------------------
request:
  max_post_params: 64
  max_post_size: 2048

# Model to load -----------------------------
model:
  name: ModelName

# AccessControl -----------------------------
access:
  controller: _base.controller.{System}AccessController/{System}AccessController

# Response -----------------------------------
response:
  404: '/_base/404.tpl'
  forbidden: '/_base/forbidden.tpl'
  onBeforeDisplay: _base.controller.{PageLoader}/{PageLoader}::onBeforeDisplay
