# URL ---------------------------------------
request:
  max_post_params: 64
  max_post_size: 2048

# Model to load -----------------------------
model:
  name: ModelName

# AccessControl -----------------------------
access:
  controller: _base.controller.{System}AccessController/{System}AccessController

# Response ----------------------------------
response:
  onBeforeDisplay: _base.controller.{System}Response/{System}Response::onBeforeDisplay
  onPageNotFound: _base.controller.{System}Response/{System}Response::onPageNotFound
  onAccessDenied: _base.controller.{System}Response/{System}Response::onAccessDenied
  onForbiddenAccess: _base.controller.{System}Response/{System}Response::onForbiddenAccess
