# URL ---------------------------------------
request:
  max_post_params: 64
  max_post_size: 2048

# Response ----------------------------------
response:
  onBeforeDisplay: {System}\Events\ResponseEvents::onBeforeDisplay
  onPageNotFound: {System}\Events\ResponseEvents::onPageNotFound
  onAccessDenied: {System}\Events\ResponseEvents::onAccessDenied
  onForbiddenAccess: {System}\Events\ResponseEvents::onForbiddenAccess
