# URL ---------------------------------------
request:
  max_post_params: 64
  max_post_size: 2048

# Response ----------------------------------
response:
  onBeforeDisplay: {SystemName}\System\Events\ResponseEvents::onBeforeDisplay
  onPageNotFound: {SystemName}\System\Events\ResponseEvents::onPageNotFound
  onAccessDenied: {SystemName}\System\Events\ResponseEvents::onAccessDenied
  onForbiddenAccess: {SystemName}\System\Events\ResponseEvents::onForbiddenAccess
