## Router for CMD System

cmd.dashboard:
  url: '/'
  handler: 'CMD\Controller\Dashboard\DashboardController::Show'
  method: 'GET'

cmd.fonts:
  url: '/fonts/icons'
  handler: 'CMD\Controller\Dashboard\DashboardController::GetFonts'
  method: 'GET'

## ----------- PACKAGES ------------------------------------
cmd.systems:
  url: '/app-systems'
  handler: 'CMD\Controller\Systems\SystemsController::ShowSystems'
  method: 'GET'

cmd.systems.new:
  url: '/app-systems/new'
  handler: 'CMD\Controller\Systems\SystemsController::NewSystem'
  method: 'GET'

cmd.systems.add:
  url: '/app-systems/add'
  handler: 'CMD\Controller\Systems\SystemsController::Add'
  method: 'POST'

cmd.systems.del:
  url: '/app-systems/del'
  handler: 'CMD\Controller\Systems\SystemsController::Del'
  method: 'POST'

## ----------- MODELS ------------------------------------
cmd.models:
  url: '/models'
  handler: 'CMD\Controller\Models\ModelsController::ShowModels'
  method: 'GET'

cmd.models.new:
  url: '/models/new'
  handler: 'CMD\Controller\Models\ModelsController::NewModel'
  method: 'GET'

cmd.models.add:
  url: '/models/add'
  handler: 'CMD\Controller\Models\ModelsController::Add'
  method: 'POST'

cmd.models.del:
  url: '/models/del'
  handler: 'CMD\Controller\Models\ModelsController::Del'
  method: 'POST'

## ----------- ROUTER ------------------------------------
cmd.router:
  url: '/app-systems/routes?system={system}'
  handler: 'CMD\Controller\Routes\RoutesController::ManageRouter'
  method: 'GET'

cmd.router.generate-all:
  url: '/app-systems/routes/generate-all'
  handler: 'CMD\Controller\Routes\RoutesController::GenerateAll'
  method: 'POST'

cmd.router.generate-rule:
  url: '/app-systems/routes/generate-rule'
  handler: 'CMD\Controller\Routes\RoutesController::GenerateRule'
  method: 'POST'

## ----------- SAMPLES ------------------------------------
cmd.samples:
  url: '/samples'
  handler: 'samples.controller.samples/Samples::Show'
  method: 'GET'